### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ryankosta** [UDXS/markdown-parser#2]
The next character after backslashes should be ignored
```
# Title
\[link1](https://something.com)
link2
```
If the link is inside single backticks it should be ignored
```
# Title

`[link1](https://something.com)`
[link2](some-thing.html)
```
If the link is inside three backticks (can span multiple lines) should be ignored. (I genuinely cant get git's markdown to render this so just imagine a code block with a link it).

**Comment by UDXS** [comment]
Both issues fixed
